---
- name: Add packages.sury.org/php APT key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_distribution_version|int <= 12

- name: Install debsuryorg-archive-keyring
  apt:
    deb: https://packages.sury.org/debsuryorg-archive-keyring.deb
    state: present
  when: ansible_distribution_version|int >= 13

- name: Add packages.sury.org/php APT repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    mode: 0644
    filename: php.list
  when: ansible_distribution_version|int <= 12

- name: Add packages.sury.org/php APT repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    mode: 0644
    filename: php.list
  when: ansible_distribution_version|int >= 13
