---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: ../../requirements.yml
    requirements-file: ../../requirements.yml

driver:
  name: podman

platforms:

  - name: ubuntu22
    image: ubuntu:jammy
    command: "sleep infinity"
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: ubuntu24
    image: ubuntu:noble
    command: "sleep infinity"
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: ubuntu26
    image: ubuntu:resolute
    command: "sleep infinity"
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: debian11
    image: debian:bullseye-slim
    command: "sleep infinity"
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: debian12
    image: debian:bookworm-slim
    command: "sleep infinity"
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: debian13
    image: debian:trixie-slim
    command: "sleep infinity"
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
        - --inventory=/path/to/inventory.yml
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
    cleanup: cleanup.yml
    prepare: prepare.yml
    side_effect: side_effect.yml
    verify: verify.yml

scenario:
  name: linux
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
