---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    php_default_version: 8.6

    php:
     - version: php86
       modules_extra: "{{ php_versions['php86'].all_modules  }}"
       #modules_extra: "{{ php_versions['php86'].all_modules | difference(['yac', 'gmagick']) }}"

  tasks:
    - name: Install packages
      apt:
        pkg:
          - gpg
          - apt-utils
        update_cache: yes
        state: present

    - name: Apply role under test
      ansible.builtin.include_role:
        name: lukasic.php
