---

name: Molecule

on:
  push:
    branches:
      - main
      - fix-actions-*
      - feat-actions-*
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu26
          - debian13
          - ubuntu24
          - debian12
          - ubuntu22
          - debian11
    steps:
      - name: Checkout repository
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth 1 origin ${{ github.sha }}
          git checkout FETCH_HEAD

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Install Ansible + Molecule
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible-core "molecule" "molecule-plugins[podman]"
          ansible-galaxy collection install containers.podman

      - name: Run molecule scenario matrix-versions
        run: molecule test -s matrix-versions
        env:
          ANSIBLE_FORCE_COLOR: "1"
          PY_COLORS: "1"
          MOLECULE_PLATFORM_NAME: ${{ matrix.platform }}
